### ISSUE TITLE
Avoid render empty div for component

### ISSUE THREAD

**Issue by multivoltage** [allevo/seqflow-js#18]
Using  `renderSync` with jsx
```jsx
async function Button(this: SeqflowFunctionContext) {
	this.renderSync(<button id="increment">hi</button>);
}

export async function Main(this: SeqflowFunctionContext) {
	this.renderSync(<Button />)
}

start(document.getElementById("root"), Main, undefined, {});
```

produces `div#root => div => button#increment`.

This happends inside `createDOMElement` function.

Is this behavior wanted?

**Comment by allevo** [comment]
Hi!
Currently, the `div` is required because SeqFlow always needs a valid HTML element for children. With it, the parent can easily attach events to children.
Otherwise, it could be challenging to handle edge cases like:
- the child waits for a while to render their content.
```tsx
async function Button(this: SeqflowFunctionContext) {
        await new Promise(res => setTimeout(res, 1000)) // just wait for a while
	this.renderSync(<button id="increment">hi</button>);
}
export async function Main(this: SeqflowFunctionContext) {
        const button = <Button />
	this.renderSync(button)
	const events = this.waitEvents('click', { el: button }) // <--- we can do this?
	for await (const ev of events) {
		console.log('new event', ev)
	}
}
```
- the child replaces its content with a new one. What should happen to the attached handlers?
```tsx
async function Button(this: SeqflowFunctionContext) {
	this.renderSync(<button id="increment">hi</button>);
        await new Promise(res => setTimeout(res, 1000)) // just wait for a while
	this.renderSync(<button id="increment">hello</button>);
}
export async function Main(this: SeqflowFunctionContext) {
        const button = <Button />
	this.renderSync(button)
	const events = this.waitEvents('click', { el: button }) // <--- What happen here when `Button` re-render itself?
	for await (const ev of events) {
		console.log('new event', ev)
	}
}
```

The above list is just an example. There are also other edge cases.

SeqFlow allows to put classes on that div to customize the look and feel. For instance, you can write something like:
```tsx
async function Button(this: SeqflowFunctionContext) {
	this._el.classList.add("another-class") // put a class generically valid, independent where this component is put
	this.renderSync(<button id="increment">hi</button>);
}

export async function Main(this: SeqflowFunctionContext) {
	this.renderSync(<Button  wrapperClass="myclass" />) // `wrapperClass` allows to specify classes that depend on the parent, like width or positions.
}
```

Some examples of the usage:
- https://github.com/search?q=repo:allevo/seqflow-js%20wrapperClass&type=code
- https://github.com/search?q=repo:allevo/seqflow-js%20this._el.classList&type=code

**Comment by multivoltage** [comment]
It' true.
But maybe to ensure consistency it better to add a div also for renderSync with non component method?
Thank for excellent explanation. I will close it :)
